### PR TITLE
Merge 4.1.0 branch into master

### PR DESCRIPTION
**Pull request by smillidge**

### CODE REVIEW

**Comment by hs536** [comment]
Hi @smillidge 
I may have missed the discussion, why did you close this PR?

**Comment by smillidge** [comment]
No idea I think because it was created by the bot

**Comment by hs536** [comment]
I think this PR should be merged to master in order to clarify the latest version. I'm not a committer of this project, so I cannot reopen and merge. Could you help? @smillidge @russgold

**Comment by smillidge** [comment]
@hs536 there's a conflict on the pom. If you have time can you resolve otherwise I can do it in a day or so.

**Comment by hs536** [comment]
@smillidge  Sure. I created a new PR that was resolved the conflict :)  https://github.com/eclipse-ee4j/orb-gmbal-pfl/pull/32

**Pull request merged**
