### PR TITLE
remove multi-release jar contents

### PR DESCRIPTION
**Pull request by russgold**
After doing a release dry-run, I noticed that we had switched the builds to use JDK11, indicating that JDK8 will no longer be supported. That means that we can simplify this project by dropping the MR features: the JDK team has shown me how to get JDK22 to work without using the new functionality added in JDK15.

This simplifies the build and also commits to JDK11 by failing on any attempt to build with a lower JDK.

There is a method that was planned to be dropped in JDK11, but the orb is still using it, so I am keeping it for now.

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Comment by pzygielo** [comment]
> we had switched the builds to use JDK11, indicating that JDK8 will no longer be supported

I fail to understand that. Main sources of the project were still targeting 1.8, weren't they? (via maven-compiler-plugin configuration).

As this seems to be the source for this change, I'd like to know more.

----

The problem I see however is that for
- #49

to be included in the artifact the JDK used to build PFL should be switched to 17 at least - to activate `compile-java17` profile and produce `Bridge.class` in version 17.

**Comment by russgold** [comment]
> > we had switched the builds to use JDK11, indicating that JDK8 will no longer be supported
> 
> I fail to understand that. Main sources of the project were still targeting 1.8, weren't they? (via maven-compiler-plugin configuration).

The compiler plugin specifies
```
                <configuration>
                    <source>${base.java.version}</source>
                    <target>${base.java.version}</target>
                </configuration>
```
and this change sets _base.java.version_ to 11.

> 
> As this seems to be the source for this change, I'd like to know more.

It is possible that I have misunderstood, but I note that the Jenkins configuration used to build the project for release had been changed to use JDK11. I assumed from that that we were dropping JDK support, but had not made all of the appropriate changes. 

> 
> The problem I see however is that for
> 
> * [Support jdk 22 #49](https://github.com/eclipse-ee4j/orb-gmbal-pfl/pull/49)
> 
> to be included in the artifact the JDK used to build PFL should be switched to 17 at least - to activate `compile-java17` profile and produce `Bridge.class` in version 17.

It turns out that I'd had some miscommunications with the JDK team. JDK22 will remove Unsafe.ensureClassInitialized(Class<?>), and was initially advised to use instead MethodHandles.Lookup.ensureInitialized(Class<?>), which was added in JDK15 - so I added a version 17 Bridge. To get that, though, I need an anchor class (a class in the same package), which makes sense when creating a new class, but does not work when trying to read the _serialPersistentFields_ field.

So they told me instead to use
```
Class.forName(cl.getName(), true, cl.getClassLoader());
```

which doesn't actually need a version 17 Bridge class.

**Comment by pzygielo** [comment]
> > > we had switched the builds to use JDK11, indicating that JDK8 will no longer be supported
> > 
> > 
> > I fail to understand that. Main sources of the project were still targeting 1.8, weren't they? (via maven-compiler-plugin configuration).
> 
> The compiler plugin specifies
> 
> ```
>                 <configuration>
>                     <source>${base.java.version}</source>
>                     <target>${base.java.version}</target>
>                 </configuration>
> ```
> 
> and this change sets _base.java.version_ to 11.

>> I noticed that we had switched the builds to use JDK11

This suggested to me that order:
1. noticed JDK11 in Jenkins,
2. changed property in maven.

> I assumed from that that we were dropping JDK 8 support

Why? The build uses JDK8 from toolchain and configures compiler to produce class files in 1.8 version still. So for maven execution one JVM is used and separate one for compilation. The JDK defined in Jenkinsfile is used to start maven.

> that the Jenkins configuration used to build the project for release had been changed to use JDK11

It had to - to activate profile to actually produce JDK11-level Bridge version.

> Creating an MR jar requires multiple JDKs - one for the main code, and one for each of the additional releases, selected via toolchains.

That doesn't have to be that way. The latest compiler with proper `--release` flags would do for all versions I believe.

> I should revert the Jenkins change

Please check how profiles in maven are set up. If you lower the JDK that maven starts with - the profile activating higher version will not trigger and the jar will have only base version. (Assuming skipping tests, check below.)

> I should revert the Jenkins change

To have #49 in the final built jar the JDK used in build should be bumped to 17 at least.

With maven started with JDK8 - it's:
```
$ jar tf pfl-basic/target/pfl-basic-5.0.0-SNAPSHOT.jar | grep Bridge
org/glassfish/pfl/basic/reflection/BridgeBase$1.class
org/glassfish/pfl/basic/reflection/BridgeBase.class
org/glassfish/pfl/basic/reflection/Bridge$1.class
org/glassfish/pfl/basic/reflection/BridgePermission.class
org/glassfish/pfl/basic/reflection/Bridge.class
org/glassfish/pfl/basic/reflection/Bridge$2.class
```

with JDK11:
```
$ jar tf pfl-basic/target/pfl-basic-5.0.0-SNAPSHOT.jar | grep Bridge
org/glassfish/pfl/basic/reflection/BridgeBase.class
org/glassfish/pfl/basic/reflection/BridgePermission.class
org/glassfish/pfl/basic/reflection/Bridge.class
META-INF/versions/11/org/glassfish/pfl/basic/reflection/Bridge.class
META-INF/versions/9/org/glassfish/pfl/basic/reflection/Bridge.class
org/glassfish/pfl/basic/reflection/BridgeBase$1.class
org/glassfish/pfl/basic/reflection/Bridge$2.class
org/glassfish/pfl/basic/reflection/Bridge$1.class
```

with JDK17:
```
$ jar tf pfl-basic/target/pfl-basic-5.0.0-SNAPSHOT.jar | grep Bridge
org/glassfish/pfl/basic/reflection/BridgeBase$1.class
org/glassfish/pfl/basic/reflection/Bridge$2.class
org/glassfish/pfl/basic/reflection/BridgeBase.class
org/glassfish/pfl/basic/reflection/Bridge$1.class
org/glassfish/pfl/basic/reflection/BridgePermission.class
org/glassfish/pfl/basic/reflection/Bridge.class
META-INF/versions/11/org/glassfish/pfl/basic/reflection/Bridge.class
META-INF/versions/17/org/glassfish/pfl/basic/reflection/Bridge.class
META-INF/versions/9/org/glassfish/pfl/basic/reflection/Bridge.class
```

Observe: `META-INF/versions`.

So the results vary, regardless of toolchain JDKs, but depending on JDK used to start maven. This activates profiles that make executions to execute (or not). And I can't see in Jenkins jobs the explicit profile activation.

Also - with JDK8 locally I'm getting
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BridgeTest.createOptionalDataException » NoClassDefFound Could not initialize ...
[ERROR]   BridgeTest.getBoolean » NoClassDefFound Could not initialize class org.glassfi...
[ERROR]   BridgeTest.getByte » NoClassDefFound Could not initialize class org.glassfish....
```

----

I'm not against dropping 8 or MR or toolchains or even aginst this change.

Just can't understand the reason provided.

**Comment by russgold** [comment]
Hmm... I realize that I hadn't documented how the toolchains and jdk were supposed to interact, and had forgotten. As implemented, you do indeed need to build with jdk11 to get the 11 version added. That means that the Jenkins change had nothing to do with dropping jdk 8 support. 

Thanks for the review. The change is indeed wrong. I will submit a simpler one to address the actual issues. The toolchains issue can be addressed later.

**Pull request closed without merging**
